name: Code Quality Analysis

on: [ push, pull_request ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v5

      - name: Run tests and collect coverage
        run: vendor/bin/phpunit --coverage-clover clover.xml

      - name: Upload coverage to Codacy
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r clover.xml