name: Code Quality Analysis

on: [ push, pull_request ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up php 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer self-update && composer install && composer dump-autoload

      - name: Run tests and collect coverage
        run: vendor/bin/phpunit --coverage-clover clover.xml

      - name: Upload coverage to Codacy
        run: |
          export CODACY_API_TOKEN=${{ secrets.CODACY_API_TOKEN }}
          export CODACY_ORGANIZATION_PROVIDER=gh
          export CODACY_USERNAME=studoo-app
          export CODACY_PROJECT_NAME=ecole-directe-api
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r clover.xml
