name: Testing PHP 8.1

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up php 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer self-update && composer install && composer dump-autoload

      - name: Run tests and collect coverage
        run: vendor/bin/phpunit

      - name: Install & run API
        run: |
          git clone https://github.com/studoo-app/mock-ecole-directe-api.git
          cd mock-ecole-directe-api && composer install && php -S localhost:80 -t api &

      - name: Test API
        run: |
          curl --request POST \
          --url http://localhost:80/v3/login \
          --header 'Content-Type: text/plain' \
          --data 'data={"identifiant":"jeremy","motdepasse":"test"}' > curl_result_docker
          cat curl_result_docker