name: Testing PHP 8.1

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      mock-api:
        image: bfoujols/mock-api-ecole-directe:v0.1.0-dev
        ports:
          - 80

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up php 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer self-update && composer install && composer dump-autoload

      - name: Run tests and collect coverage
        run: vendor/bin/phpunit

      - name: Test API
        run: |
          wget --quiet \
          --method POST \
          --header 'Content-Type: text/plain' \
          --body-data 'data={"identifiant":"jeremy","motdepasse":"test"}' \
          --output-document \
          - http://mock-api:80/v3/login