name: Testing PHP 8.1

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      mock-api:
        image: bfoujols/mock-api-ecole-directe:v0.1.0-dev
        ports:
          - 80:80

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up php 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer self-update && composer install && composer dump-autoload

      - name: Run tests and collect coverage
        run: vendor/bin/phpunit

      - name: Test API
        run: |
          apt-get update; apt-get install curl -y
          curl --request POST \
          --url http://mock-api:80/v3/login \
          --header 'Content-Type: text/plain' \
          --data 'data={"identifiant":"jeremy","motdepasse":"test"}' > curl_result_docker
          cat curl_result_docker