name: Testing PHP 8.1

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up php 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer self-update && composer install && composer dump-autoload

      - name: Install & run API
        run: |
          git clone https://github.com/studoo-app/mock-ecole-directe-api.git
          cd mock-ecole-directe-api && composer install && php -S localhost:9042 -t api &

      - name: Run tests and collect coverage
        run: vendor/bin/phpunit
