name: Testing PHP 8.1

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      mock-api:
        image: bfoujols/mock-api-ecole-directe:v0.1.0-dev
        ports:
          - 80:80
        options: --add-host mockapiecoledirecte:127.0.0.1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up php 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer self-update && composer install && composer dump-autoload

      - name: Run tests and collect coverage
        run: vendor/bin/phpunit

      - name: Test start API
        run: |
          timeout=60
          while [ $timeout -gt 0 ]; do
            curl -I http://mockapiecoledirecte:${{ job.services.mock-api.ports['80'] }} && break
            echo "Waiting for API service..."
            timeout=$((timeout - 1))
            sleep 1
          done
          if [ $timeout -eq 0 ]; then
            echo "API service did not start in time"
            exit 1
          fi

      - name: Test API
        run: |
          curl --request POST \
            --url http://mockapiecoledirecte:${{ job.services.mock-api.ports['80'] }}/v3/login \
            --header 'Content-Type: text/plain' \
            --data 'data={"identifiant":"jeremy","motdepasse":"test"}'